apiVersion: v1

kind: PersistentVolumeClaim

metadata:

  name: n8n-pvc

  namespace: n8n-server

spec:

  accessModes:
    - ReadWriteOnce

  storageClassName: local-path

  resources:

    requests:
      storage: 5Gi

