apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
  namespace: mysql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server
  template:
    metadata:
      labels:
        app: mysql-server
        name: mysql-server
    spec:
      # nodeSelector:
      #   node-type: worker
      #   kubernetes.io/arch: arm64
      containers:
      - name: mysql-server
        image: ubuntu/mysql:edge
        imagePullPolicy: "IfNotPresent"
        ports:
          - name: mysql-server
            containerPort: 3306
        volumeMounts:
          - name: mysql-config-volume
            mountPath: /etc/mysql/mysql.conf.d/my-custom.cnf
            subPath: my-custom.cnf        
          - name: mysql-storage
            mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "secret"
          - name: MYSQL_INITSB_SKIP_TZINFO
            value: "yes"
      volumes:
        - name: mysql-config-volume
          configMap:
            name: mysql-config
            items:
            - key: main-config
              path: my-custom.cnf      
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

