apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  namespace: mysql-server
spec:
  selector:
    app: mysql-server
  type: LoadBalancer
  ports:
    - name: mysql-port
      protocol: TCP
      port: 3306
      targetPort: 3306
  #loadBalancerIP: 192.168.68.200

