apiVersion: batch/v1

kind: CronJob

metadata:
  name: postgresql-backup-cron-job
  namespace: pg-backup

spec:
  
  schedule: "0 */12 * * *"

  successfulJobsHistoryLimit: 1
  
  failedJobsHistoryLimit: 1  
  
  jobTemplate:
  
    spec:

      template:

        spec:

          containers:
          - name: postgresql-backup-job
            image: ghcr.io/zaherg/postgres_backup:latest
            imagePullPolicy: Always
            env:
            - name: POSTGRES_DATABASE
              value: ""
            - name: POSTGRES_HOST
              value: ""
            - name: POSTGRES_PORT
              value: ""
            - name: POSTGRES_PASSWORD
              value: ""
            - name: POSTGRES_USER
              value: ""
            - name: S3_ACCESS_KEY_ID
              value: ""
            - name: S3_SECRET_ACCESS_KEY
              value: ""
            - name: S3_BUCKET
              value: ""
            - name: S3_ENDPOINT
              value: ""
            - name: S3_PREFIX
              value: ""
            - name: SCHEDULE
              value: ""
          restartPolicy: OnFailure
      
      backoffLimit: 3