apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: mastodon-pvc
  namespace: mastodon-server

spec:
  accessModes:
    - ReadWriteOnce
  
  storageClassName: longhorn

  resources:

    requests:
      storage: 5Gi