apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  namespace: redis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
        name: redis-server
    spec:
      # nodeSelector:
      #   node-type: worker
      #   kubernetes.io/arch: arm64
      containers:
      - name: redis-server
        image: redis:latest
        imagePullPolicy: "IfNotPresent"
        args: ["--appendonly", "yes"]
        ports:
          - name: redis-server
            containerPort: 6379
        volumeMounts:
          - name: redis-storage
            mountPath: /data
        env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc

