apiVersion: v1
kind: Service
metadata:
  name: postgres-server
  namespace: postgres-server
spec:
  selector:
    app: postgres-server
  type: LoadBalancer
  ports:
    - name: postgres-port
      protocol: TCP
      port: 5432
      targetPort: 5432
  #loadBalancerIP: 192.168.68.200

