apiVersion: v1

kind: PersistentVolumeClaim

metadata:

  name: meilisearch-pvc

  namespace: meilisearch-server

spec:

  accessModes:
    - ReadWriteOnce

  storageClassName: local-path

  resources:

    requests:
      storage: 5Gi

