apiVersion: v1

kind: Service

metadata:

  name: meilisearch

  namespace: meilisearch-server

spec:

  selector:
    app: meilisearch

  type: LoadBalancer

  ports:

    - name: meilisearch-port
      protocol: TCP
      port: 7700
      targetPort: 7700
  #loadBalancerIP: 192.168.68.200

