apiVersion: v1

kind: PersistentVolumeClaim

metadata:

  name: redis-pvc

  namespace: redis-server

spec:

  accessModes:
    - ReadWriteOnce

  storageClassName: local-path

  resources:

    requests:
      storage: 5Gi

